name: devops

on:
  push:
    branches:
      - main

jobs:
  devops:
    name: devops
    runs-on: ubuntu-latest

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt' 
        java-version: '11'
        cache: 'maven'
    
    - name: Run unit tests
      run: | 
        mvn test
      
    - name: Build and push Docker image
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: chillaso/devops
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'

